---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
date: "December 2021"
output: pdf_document
---

# Practice Assignment 3

### Introduction

This is the third assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Download the Data Expo 2009 data from the [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HG7NV7) and construct an SQLite Database called airline2.db with the following tables:

1. ontime (with the data from 2000 to 2005 – including [2000](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/YGU3TD&version=1.0), [2001](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/CI5CEM&version=1.0), [2002](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/OWJXH3&version=1.0), [2003](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/KM2QOA&version=1.0), [2004](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/CCAZGT&version=1.0) and [2005](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/JTFT25&version=1.0))
2. airports (with the data in [airports.csv](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/XTPZZY&version=1.0))
3. carriers (with the data in [carriers.csv](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/3NOQ6Q&version=1.0))
4. planes (with the data in [plane-data.csv](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HG7NV7/XXSL8A&version=1.0))

Create a GitHub repository called “st2195_assignment_3” that includes

* a README.md file with a short markdown description of this assignment and a reference to the Data Expo 2009 data, and the Harvard Dataverse [1 point]

* a folder called “r_sql” with a R code for constructing the database (from the csv inputs) and replicating the queries in the practice quiz. The latter should be done both using DBI and dplyr notation [1.75 points each]

* a folder called “python_sql” with a Python version of the code in point 2, based on sqlite3 [1.75 points]

* a simplified solution for the query in Q4 in either R or Python (placed either in 
the R or Python *_sql folder) [1.75 points]

Note that the database file should not be placed in the GitHub repository (it is quite large). Also, the R and Python scripts should save the output of the queries in csv within their respective folders [1 point each].